/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class ofEntryEventArgs
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "events/ofEvents.h"


/** Set attributes (key, value)
 * 
 */
static int ofEntryEventArgs__set_(lua_State *L) {

  ofEntryEventArgs *self = *((ofEntryEventArgs **)dub_checksdata_n(L, 1, "ofEntryEventArgs"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "state")) break;
      self->state = luaL_checkint(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int ofEntryEventArgs__get_(lua_State *L) {

  ofEntryEventArgs *self = *((ofEntryEventArgs **)dub_checksdata_n(L, 1, "ofEntryEventArgs", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "state")) break;
      lua_pushnumber(L, self->state);
      return 1;
    }
  }
  return 0;
}

/** Cast (class_name)
 * 
 */
static int ofEntryEventArgs__cast_(lua_State *L) {

  ofEntryEventArgs *self = *((ofEntryEventArgs **)dub_checksdata_n(L, 1, "ofEntryEventArgs"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "ofEventArgs")) break;
      *retval__ = static_cast<ofEventArgs *>(self);
      return 1;
    }
  }
  return 0;
}

/** ofEntryEventArgs()
 * 
 */
static int ofEntryEventArgs_ofEntryEventArgs(lua_State *L) {
  try {
    ofEntryEventArgs *retval__ = new ofEntryEventArgs();
    dub_pushudata(L, retval__, "ofEntryEventArgs", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int ofEntryEventArgs___tostring(lua_State *L) {
  ofEntryEventArgs *self = *((ofEntryEventArgs **)dub_checksdata_n(L, 1, "ofEntryEventArgs"));
  lua_pushfstring(L, "ofEntryEventArgs: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg ofEntryEventArgs_member_methods[] = {
  { "__newindex"   , ofEntryEventArgs__set_ },
  { "__index"      , ofEntryEventArgs__get_ },
  { "_cast_"       , ofEntryEventArgs__cast_ },
  { "new"          , ofEntryEventArgs_ofEntryEventArgs },
  { "__tostring"   , ofEntryEventArgs___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_ofEntryEventArgs(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "ofEntryEventArgs");
  // <mt>

  // register member methods
  luaL_register(L, NULL, ofEntryEventArgs_member_methods);
  // save meta-table in _G
  dub_register(L, "_G", "ofEntryEventArgs", "ofEntryEventArgs");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
