/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class ofFloatImage
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "api/openFrameworks/types/ofBaseTypes.h"


/** ofFloatImage()
 * 
 */
static int ofFloatImage_ofFloatImage(lua_State *L) {
  try {
    ofFloatImage *retval__ = new ofFloatImage();
    dub_pushudata(L, retval__, "ofFloatImage", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub_error(L);
}

/** ~ofImage_()
 * 
 */
static int ofFloatImage__ofFloatImage(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "ofFloatImage"));
    if (userdata->gc) {
      ofFloatImage *self = (ofFloatImage *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int ofFloatImage___tostring(lua_State *L) {
  ofFloatImage *self = *((ofFloatImage **)dub_checksdata_n(L, 1, "ofFloatImage"));
  lua_pushfstring(L, "ofFloatImage: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg ofFloatImage_member_methods[] = {
  { "new"          , ofFloatImage_ofFloatImage },
  { "__gc"         , ofFloatImage__ofFloatImage },
  { "__tostring"   , ofFloatImage___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_ofFloatImage(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "ofFloatImage");
  // <mt>

  // register member methods
  luaL_register(L, NULL, ofFloatImage_member_methods);
  // save meta-table in _G
  dub_register(L, "_G", "ofFloatImage", "ofFloatImage");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
