/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class ofLogWarning
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "api/openFrameworks/utils/ofLog.h"


/** ~ofLogWarning()
 * 
 */
static int ofLogWarning__ofLogWarning(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "ofLogWarning"));
    if (userdata->gc) {
      ofLogWarning *self = (ofLogWarning *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub_error(L);
}

/** Cast (class_name)
 * 
 */
static int ofLogWarning__cast_(lua_State *L) {

  ofLogWarning *self = *((ofLogWarning **)dub_checksdata_n(L, 1, "ofLogWarning"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "ofLog")) break;
      *retval__ = static_cast<ofLog *>(self);
      return 1;
    }
  }
  return 0;
}

/** ofLogWarning::ofLogWarning(const string &module="OF")
 * api/openFrameworks/utils/ofLog.h:129
 */
static int ofLogWarning_ofLogWarning(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      string *module = *((string **)dub_checksdata(L, 1, "string"));
      string *message = *((string **)dub_checksdata(L, 2, "string"));
      ofLogWarning *retval__ = new ofLogWarning(*module, *message);
      dub_pushudata(L, retval__, "ofLogWarning", true);
      return 1;
    } else if (top__ >= 1) {
      string *module = *((string **)dub_checksdata(L, 1, "string"));
      ofLogWarning *retval__ = new ofLogWarning(*module);
      dub_pushudata(L, retval__, "ofLogWarning", true);
      return 1;
    } else {
      ofLogWarning *retval__ = new ofLogWarning();
      dub_pushudata(L, retval__, "ofLogWarning", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int ofLogWarning___tostring(lua_State *L) {
  ofLogWarning *self = *((ofLogWarning **)dub_checksdata_n(L, 1, "ofLogWarning"));
  lua_pushfstring(L, "ofLogWarning: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg ofLogWarning_member_methods[] = {
  { "__gc"         , ofLogWarning__ofLogWarning },
  { "_cast_"       , ofLogWarning__cast_  },
  { "new"          , ofLogWarning_ofLogWarning },
  { "__tostring"   , ofLogWarning___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_ofLogWarning(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "ofLogWarning");
  // <mt>

  // register member methods
  luaL_register(L, NULL, ofLogWarning_member_methods);
  // save meta-table in _G
  dub_register(L, "_G", "ofLogWarning", "ofLogWarning");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
